name 'install_mongo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_mongo'
long_description 'Installs/Configures install_mongo'
version '0.1.0'
